"""empty message

Revision ID: 059e53d21876
Revises: 1c1e68551b06
Create Date: 2020-05-08 12:03:23.032764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059e53d21876'
down_revision = '1c1e68551b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('icon', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'icon')
    # ### end Alembic commands ###
