"""empty message

Revision ID: 1c1e68551b06
Revises: 8589e76fe161
Create Date: 2020-05-08 11:55:16.105903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c1e68551b06'
down_revision = '8589e76fe161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('symbol', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'symbol')
    # ### end Alembic commands ###
