"""empty message

Revision ID: 290730c63670
Revises: 
Create Date: 2020-07-10 18:41:03.932368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290730c63670'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'trade_side', 'trade', ['trade_uuid'], ['uuid'])
    op.create_foreign_key(None, 'trade_side', 'order', ['order_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trade_side', type_='foreignkey')
    op.drop_constraint(None, 'trade_side', type_='foreignkey')
    # ### end Alembic commands ###
