"""empty message

Revision ID: 4232cb73db50
Revises: e109490563bf
Create Date: 2020-06-29 15:38:23.113972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4232cb73db50'
down_revision = 'e109490563bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('vol30d', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_asset_account_id'), 'account_asset', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_asset_asset_id'), 'account_asset', ['asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_asset_asset_id'), table_name='account_asset')
    op.drop_index(op.f('ix_account_asset_account_id'), table_name='account_asset')
    op.drop_table('account_asset')
    # ### end Alembic commands ###
