"""empty message

Revision ID: 5105d817bdbd
Revises: d4c50cf2e632
Create Date: 2020-05-04 16:35:06.760003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5105d817bdbd'
down_revision = 'd4c50cf2e632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('owner', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owner', 'title')
    op.drop_column('owner', 'email')
    # ### end Alembic commands ###
