"""empty message

Revision ID: 6723f7cc86f8
Revises: 
Create Date: 2020-06-29 11:10:03.940457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6723f7cc86f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_account_uuid'), 'account', ['uuid'], unique=True)
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('scale', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_uuid'), 'asset', ['uuid'], unique=True)
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=20), nullable=False),
    sa.Column('method', sa.Enum('place-order', 'cancel-order', 'deposit', 'withdraw'), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'done'), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_uuid'), 'event', ['uuid'], unique=True)
    op.create_table('market',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=15), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('asset1', sa.Integer(), nullable=False),
    sa.Column('asset2', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset1'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['asset2'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_uuid'), 'market', ['uuid'], unique=True)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=20), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('balance', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('side', sa.Enum('buy', 'sell'), nullable=False),
    sa.Column('type', sa.Enum('limit', 'market'), nullable=False),
    sa.Column('status', sa.Enum('open', 'partial', 'closed', 'canceled'), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['market.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_uuid'), 'order', ['uuid'], unique=True)
    op.create_table('trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=20), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['market.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_created'), 'trade', ['created'], unique=False)
    op.create_index(op.f('ix_trade_uuid'), 'trade', ['uuid'], unique=True)
    op.create_table('trade_side',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=20), nullable=False),
    sa.Column('type', sa.Enum('maker', 'taker'), nullable=False),
    sa.Column('trade_uuid', sa.String(length=20), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('order_uuid', sa.String(length=20), nullable=True),
    sa.Column('fee_rate', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['order_uuid'], ['order.uuid'], ),
    sa.ForeignKeyConstraint(['trade_uuid'], ['trade.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_side_created'), 'trade_side', ['created'], unique=False)
    op.create_index(op.f('ix_trade_side_uuid'), 'trade_side', ['uuid'], unique=True)
    op.create_table('ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=20), nullable=False),
    sa.Column('type', sa.Enum('deposit', 'withdraw', 'trade'), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('balance', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('trade_side_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['trade_side_id'], ['trade_side.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_account_id'), 'ledger', ['account_id'], unique=False)
    op.create_index(op.f('ix_ledger_uuid'), 'ledger', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_uuid'), table_name='ledger')
    op.drop_index(op.f('ix_ledger_account_id'), table_name='ledger')
    op.drop_table('ledger')
    op.drop_index(op.f('ix_trade_side_uuid'), table_name='trade_side')
    op.drop_index(op.f('ix_trade_side_created'), table_name='trade_side')
    op.drop_table('trade_side')
    op.drop_index(op.f('ix_trade_uuid'), table_name='trade')
    op.drop_index(op.f('ix_trade_created'), table_name='trade')
    op.drop_table('trade')
    op.drop_index(op.f('ix_order_uuid'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_market_uuid'), table_name='market')
    op.drop_table('market')
    op.drop_index(op.f('ix_event_uuid'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_asset_uuid'), table_name='asset')
    op.drop_table('asset')
    op.drop_index(op.f('ix_account_uuid'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
