"""empty message

Revision ID: 9dded8dae489
Revises: 50dcec974b84
Create Date: 2020-05-11 19:40:58.409055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '9dded8dae489'
down_revision = '50dcec974b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('created', sqlite.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'created')
    # ### end Alembic commands ###
