"""empty message

Revision ID: d4c50cf2e632
Revises: c58915b73ea4
Create Date: 2020-05-04 15:20:02.617248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c50cf2e632'
down_revision = 'c58915b73ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('amount_left', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'amount_left')
    # ### end Alembic commands ###
