"""add fee sched

Revision ID: e109490563bf
Revises: 6723f7cc86f8
Create Date: 2020-06-29 11:53:57.958848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e109490563bf'
down_revision = '6723f7cc86f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('trade'), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('maker', sa.Integer(), nullable=False),
    sa.Column('taker', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fee_schedule')
    # ### end Alembic commands ###
