"""add test

Revision ID: e1f66e0668d0
Revises: b48a867b46e6
Create Date: 2020-04-29 21:33:42.187581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f66e0668d0'
down_revision = 'b48a867b46e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_book', sa.Column('test', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_book', 'test')
    # ### end Alembic commands ###
