"""empty message

Revision ID: f9d0f0c0daf9
Revises: 9dded8dae489
Create Date: 2020-05-11 19:54:58.223199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d0f0c0daf9'
down_revision = '9dded8dae489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('status', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'status')
    # ### end Alembic commands ###
